[package]
name = "amp"
version = "0.1.0"
authors = ["REIS0 <aor@cesar.school>"]
edition = "2018"
license = "ISC"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
lv2 = "0.5.1"
